-- Users & Posts schema (PostgreSQL)
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
  
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS image_key  TEXT NULL,
  ADD COLUMN IF NOT EXISTS image_mime TEXT NULL,
  ADD COLUMN IF NOT EXISTS image_size INTEGER NULL;


CREATE INDEX IF NOT EXISTS idx_posts_user_id ON posts(user_id);
